development:
  facebook:
    client_id: '667205069970184'
    client_secret: 'c353ef6e2322a6342b349933651193ab'
    scope: 'email, offline_access'

  twitter:
    client_id: 7l2GOzjpGLlTj2SUF0Zww
    client_secret: fXXPPLt60SQAM7lUpZeqoJ07jYHaNNi1kpPwAsrMew

production:
  facebook:
    client_id: '1384077758490171'
    client_secret: '49cc428daa785a71e8d8b163a9210f8d'
    scope: 'email, offline_access'

  twitter:
    client_id: NAs6Vh3PtN7Pv7ULG7eCyA
    client_secret: 3E8RgvAGjCrnqynkrCPfBI6KVdIK4u9iXt8WGPVyLq0
    
test:
  facebook:
    client_id: 'dummyid'
    client_secret: 'dummysecret'
    scope: 'email, offline_access'

  twitter:
    client_id: 'dummyid'
    client_secret: 'dummysecret'

