development:
  adapter: postgresql
  encoding: unicode
  database: gf_core_development
  host: localhost
  username: gfauth
  password: test

test:
  adapter: postgresql
  encoding: unicode
  database: gf_core_test
  host: localhost
  username: gfauth
  password: test

staging:
  adapter: postgresql
  encoding: unicode
  database: gf_core
  host: localhost
  username: gfauth
  password: ex171aY555

production:
  adapter: postgresql
  encoding: unicode
  database: gf_core
  host: localhost
  username: gfauth
  password: ex171aY555
